### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by kit-johnson** [shama/grunt-beep#11]
There is no sound playing when the beep task is run.

> Running "beep" task
♪
Done.

I'm not sure how to troubleshoot this. I tested my speakers are switched on and are playing sounds.

I'm running Windows 10.

I appreciate any help!

**Comment by shama** [comment]
This prints `\x07` to the console which is the code for the system beep. You can try pressing `alt + 007` in the console to trigger it manually I believe.

To fix, search your sound settings for the default system beep and make sure it has a value. It might be in settings or in the registry.

**Comment by kit-johnson** [comment]
That was it; you've solved it. Thank you!
