### ISSUE TITLE
beep:error task keeps on executing after the first error occurs

### ISSUE THREAD

**Issue by jadjoubran** [shama/grunt-beep#6]
`tasks: [ 'jshint', 'beep:error', 'concat:js', 'uglify:app' ]`

As long as jshint didn't generate errors, beep:error will not be executed.
when jshint generates its first error, beep:error will be executed
And then even if jshint doesn't generate any errors anymore, beep:error will keep on executing everytime these tasks are triggered (currently on the watch)

**Comment by shama** [comment]
Ah because in the watch, my guess is you have `spawn: false` and each run is running in the same process. Meaning once it increments `grunt.fail.errorcount` it never decrements it. You could add a task at the end that resets `grunt.fail.errorcount = 0`.

**Comment by jadjoubran** [comment]
Worked, thanks!
I'll submit a pull request to add this to the documentation

**Comment by jadjoubran** [comment]
:D
